# Generated by Django 5.1.2 on 2025-01-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_manager_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, help_text='Укажите токен для подтверждения', max_length=100, null=True, verbose_name='Token'),
        ),
    ]
