# Generated by Django 5.1.2 on 2025-01-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailing_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingattempt',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
