# Generated by Django 5.1.2 on 2025-01-25 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_client_id_alter_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingattempt',
            name='client',
        ),
        migrations.RemoveField(
            model_name='mailingattempt',
            name='mailing',
        ),
        migrations.AlterModelOptions(
            name='mailinglog',
            options={'verbose_name': 'Журнал попытки рассылки', 'verbose_name_plural': 'Журналы попыток рассылки'},
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.client'),
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='server_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('failed', 'Failed')], max_length=20),
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='MailingAttempt',
        ),
    ]
