# Generated by Django 5.1.2 on 2024-11-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempt',
            name='status',
            field=models.BooleanField(choices=[(True, 'Успешно'), (False, 'Неудачно')]),
        ),
    ]
