# Generated by Django 5.1.2 on 2025-01-19 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_remove_mailing_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mailing.mailing'),
        ),
    ]
